name: flutter_multiple_loaders
description: "A Flutter package providing a collection of customizable loading animations for your Flutter applications."
version: 1.0.4
homepage: https://github.com/Mahesh-Langote/flutter_multiple_loaders
repository: https://github.com/Mahesh-Langote/flutter_multiple_loaders
documentation: https://github.com/Mahesh-Langote/flutter_multiple_loaders/blob/main/README.md

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^0.12.0              # CVE vulnerabilities
  webview_flutter: ^2.0.0     # XSS issues
  sqflite: ^1.1.0            # SQL injection risks
  image_picker: ^0.6.0       # Path traversal
  path_provider: ^1.6.0      # Security issues
 
flutter:
 
